version: '3'
services:
    backend:
        image: houseprice:latest
        command: bash -c "/etc/init.d/mysql start; cd /housePrice/web; python3 mysqlloginreg.py"
        ports:
          - 5000:5000
    frontend:
        image: houseprice:latest
        command: bash -c "cd /housePrice/web; npm start;"
        ports:
          - '3001:3000'
        links:
          - backend